version: '3'

services:
  order-db:
    container_name: order-db
    image: mongo:latest
    restart: always
    networks:
      - orchestrator-saga
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123123
      MONGO_INITDB_DATABASE: order-db
    ports:
      - "27017:27017"

  product-db:
    container_name: product-db
    image: postgres:latest
    restart: always
    networks:
      - orchestrator-saga
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/product-db:/var/lib/postgresql/data

  payment-db:
    container_name: payment-db
    image: postgres:latest
    restart: always
    networks:
      - orchestrator-saga
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres/payment-db:/var/lib/postgresql/data

  inventory-db:
    container_name: inventory-db
    image: postgres:latest
    restart: always
    networks:
      - orchestrator-saga
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: db
    ports:
      - "5434:5432"
    volumes:
      - ./data/postgres/inventory-db:/var/lib/postgresql/data

  kafka:
    container_name: kafka
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - orchestrator-saga
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    volumes:
      - ./data/kafka/data:/var/lib/kafka/data

  redpanda-console:
    container_name: redpanda
    image: docker.redpanda.com/vectorized/console:latest
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    ports:
      - "8081:8080"
    networks:
      - orchestrator-saga
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:29092"]
    depends_on:
      - "kafka"


  order-service:
    build: './order-service'
    container_name: order-service
    restart: always
    depends_on:
      - order-db
      - kafka
    networks:
      - orchestrator-saga
    environment:
      - KAFKA_BROKER=kafka:29092
      - MONGO_DB=mongodb://root:123123@order-db:27017/order-db
    ports:
      - "3000:3000"

  orchestrator-service:
    build: './orchestrator-service'
    container_name: orchestrator-service
    restart: always
    networks:
      - orchestrator-saga
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:29092
    ports:
      - "8080:8080"

  product-validation-service:
    build: './product-validation-service'
    container_name: product-validation-service
    restart: always
    networks:
      - orchestrator-saga
    depends_on:
      - kafka
      - product-db
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=product-db
      - DB_PORT=5432
      - DB_NAME=db
      - DB_USER=postgres
      - DB_PASSWORD=123123
    ports:
      - "8090:8090"

  inventory-service:
    build: './inventory-service'
    container_name: inventory-service
    restart: always
    networks:
      - orchestrator-saga
    depends_on:
      - kafka
      - product-db
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=inventory-db
      - DB_PORT=5432
      - DB_NAME=db
      - DB_USER=postgres
      - DB_PASSWORD=123123
    ports:
      - "8092:8092"

  payment-service:
    build: './payment-service'
    container_name: payment-service
    restart: always
    networks:
      - orchestrator-saga
    depends_on:
      - kafka
      - payment-db
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=product-db
      - DB_PORT=5432
      - DB_NAME=db
      - DB_USER=postgres
      - DB_PASSWORD=123123
    ports:
      - "8091:8091"

networks:
  orchestrator-saga:
    driver: bridge
